### ISSUE TITLE
Look into why the first websocket message isn't sent anymore in the test_websocket_process_detail_workflow test

### ISSUE THREAD

**Issue by tjeerddie** [workfloworchestrator/orchestrator-core#309] opened 2023-07-20 09:20 UTC
Follow up from https://github.com/workfloworchestrator/orchestrator-core/pull/295#discussion_r1255718233

the first receive message has been commented out because an update has changed the behaviour.

```
 # WITH AN PACKAGE UPDATE IT DOES NOT SEND THIS FIRST MESSAGE ANYMORE
 # data = websocket.receive_text()
 # process = json_loads(data)["process"]
# assert process["workflow_name"] == "long_running_workflow_py"
# assert process["status"] == ProcessStatus.RUNNING
```

**Comment by pboers1988** [comment] 2024-01-17 13:41
Marking duplicate of #394 and closing for now. We need to start using the websockets again in 2.0

**Closed by pboers1988** 2024-01-17 13:41 UTC
Labels: bug, enhancement
