### ISSUE TITLE
inputstep assignee cannot be None

### ISSUE THREAD

**Issue by Mark90** [workfloworchestrator/orchestrator-core#236] opened 2023-04-06 13:20 UTC
The assignee parameter to `inputstep()` can be left None, but this causes SQL errors (and the workflow staying in "Running") as the field is non-null in the database.

The parameter should have a sensible default, or otherwise raise an error if left None.

https://github.com/workfloworchestrator/orchestrator-core/blob/586efd493f693504b05b6883e7fef16c44b3db95/orchestrator/workflow.py#L254

**Comment by crankynetman** [comment] 2023-04-17 12:40
Apparently I missed this before, but this was just fixed in PR #244. The fix was to just make the param mandatory for now. Sorry I didn't see this before opening my issue 🤦

**Comment by crankynetman** [comment] 2023-04-17 12:41
I guess I didn't see this before, but we probably should close this as a duplicate of #243. Sorry for the duplicate issue 🤦‍♂️

**Comment by Mark90** [comment] 2023-04-17 19:12
> I guess I didn't see this before, but we probably should close this as a duplicate of #243. Sorry for the duplicate issue 🤦‍♂️

No problem at all, thanks for addressing it :)

**Closed** 2023-04-17 19:12 UTC
